constants:
  radius: 0.05
  density: 1000
  rolling_friction_coefficient: 0.007
  walls_elasticity: 0.8

sim:
  n_steps: 1000
  sim_time: 2.0
  coordinate_target: [3.0, 2.5]
  attractor_coordinate: [4.0, 3.5]
  attractor_strength: 0.
  svg_scene_path: /home/gleb/code/repos/doper/assets/two_triangles.svg
  distance_range: 500
  angle_step: 20

train:
  trainer_name: BallAttractorTrainer
  n_iters: 2000
  val_iter: 50
  logging_level: INFO
  device: cpu
  output_folder: ./output/

model:
  input_dim: 21
  output_dim: 2
  internal_dim: 50
