constants:
  radius: 0.05
  density: 1000
  rolling_friction_coefficient: 0.007
  walls_elasticity: 0.8

sim:
  n_steps: 2000
  sim_time: 2.0
  coordinate_target: [3.0, 2.5]
  attractor_coordinate: [4.0, 3.5]
  attractor_strength: 1.0
  svg_scene_path: ../assets/simple_level.svg

train:
  n_iters: 2000
  logger: DEBUG
  device: cuda

model:
  input_dim: 5
  output_dim: 2
  internal_dim: 50
